(defun color-theme-zert ()
  "Zert color theme. Created by Max Treskin <zerthurd@gmail.com> March 1 2013."
  (interactive)
  (color-theme-install
   '(color-theme-zert
     ((background-color . "#212121")
      (background-mode . dark)
      (border-color . "#000000")
      (cursor-color . "#355f35")
      (foreground-color . "color-109")
      (mouse-color . "black"))
     (default ((t (nil))))
     (bold ((t (:bold t :foreground "cyan" :weight bold))))
     (bold-italic ((t (:italic t :bold t :foreground "cyan" :slant italic :weight bold))))
     (font-lock-builtin-face ((t (:bold t :foreground "color-25"))))
     (font-lock-comment-face ((t (:foreground "color-24"))))
     (font-lock-function-name-face ((t (:foreground "#3be61e"))))
     (font-lock-keyword-face ((t (:foreground "color-196"))))
     (font-lock-preprocessor-face ((t (:foreground "color-214"))))
     (font-lock-string-face ((t (:foreground "color-202"))))
     (font-lock-type-face ((t (:foreground"color-208"))))
     (font-lock-variable-name-face ((t (:foreground "color-34"))))
     (font-lock-constant-face ((t (:foreground "color-31"))))
     (font-lock-doc-face ((t (:bold t :weight bold :foreground "red"))))
     (font-lock-warning-face ((t (:bold t :foreground "red" :weight bold))))
     (fringe ((t (:background "#000000"))))
     (highlight ((t (:background "blue"))))
     (isearch ((t (:background "blue" :foreground "cyan3"))))
     (isearch-lazy-highlight-face ((t (:background "turquoise3" :foreground "black"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "color-81"))))
     (mode-line ((t (:foreground "#000000" :background "#696969"))))
     (mouse ((t (:background "white"))))
     (region ((t (:background "#49451d"))))
     (scroll-bar ((t (nil))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (magit-item-highlight ((t (:background "gray50"))))
     (rst-level-2 ((t (:background "grey78" :foreground "black"))))
     (rst-level-3 ((t (:background "grey71" :foreground "black"))))
     (rst-level-4 ((t (:background "grey64" :foreground "black"))))
     (calendar-today ((t (:background "#eeeeee" :underline t))))
     (cperl-array ((((class color) (background light)) (:foreground "Blue" :weight bold))))
     (cperl-hash ((((class color) (background dark)) (:foreground "#55aa55"))))
     (cursor ((t (:background "white"))))
     (custom-comment ((((class grayscale color) (background light)) (:background "gray85" :slant italic))))
     (custom-documentation ((t (:family "times"))))
     (diff-added ((t (:foreground "#55aa55"))))
     (diff-file-header ((((class color) (min-colors 88) (background dark)) (:background "grey60" :foreground "blue"))))
     (diff-index ((t (:foreground "#aaaaaa"))))
     (diff-removed ((t (:foreground "brown"))))
     (dired-directory ((t (:foreground "#5555ff"))))
     (ecb-default-highlight-face ((((class color) (background dark)) (:background "#886600"))))
     (ecb-history-face ((((class color) (background dark)) (:inherit ecb-default-highlight-face :background "green"))))
     (ediff-odd-diff-A ((((class color) (min-colors 16)) (:background "Grey" :foreground "Green"))))
     (ediff-odd-diff-C ((((class color) (min-colors 16)) (:background "Grey" :foreground "Red"))))
     (erc-default-face ((t (:foreground "#777777"))) t)
     (erc-input-face ((t (:foreground "#8888FF"))))
     (erc-timestamp-face ((t (:background "black" :foreground "green" :weight bold))))
     (eshell-prompt ((t (:foreground "Blue" :weight bold))))
     (imaxima-latex-error-face ((t (:foreground "#cc3344" :underline t))))
     (info-title-1 ((t (:inherit info-title-2 :height 1.5))))
     (italic ((t (:slant italic :family "adobe-times"))))
     (jabber-activity-face ((t (:foreground "#000000"))))
     (jabber-chat-prompt-foreign ((t (:foreground "#6666ff"))))
     (jabber-chat-prompt-local ((t (:foreground "darkgreen"))))
     (jabber-chat-prompt-system ((t (:foreground "#667766"))))
     (jabber-rare-time-face ((t (:foreground "darkred" :underline t))))
     (jabber-roster-user-away ((t (:foreground "brown" :slant italic :weight normal))))
     (jabber-roster-user-offline ((t (:foreground "#aaaaaa" :slant italic :weight light))))
     (jabber-title-large ((t (:inherit variable-pitch :weight bold :height 1.5 :width ultra-expanded))))
     (jabber-title-medium ((t (:inherit variable-pitch :weight bold :height 1.0 :width expanded))))
     (jabber-title-small ((t (:inherit variable-pitch :weight bold :height 0.7 :width semi-expanded))))
     (menu ((((type x-toolkit)) (:background "#555555" :foreground "#aaaaaa" :family "xos4-terminus"))))
     (minibuffer-prompt ((t (:foreground "color-81"))))
     (mode-line ((((class color) (min-colors 88)) (:background "color-102" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:foreground "black"))))
     (nxml-attribute-local-name-face ((t (:foreground "magenta"))))
     (nxml-attribute-prefix-face ((t (:foreground "brown"))))
     (nxml-attribute-value-face ((t (:foreground "#ff9922"))))
     (nxml-element-local-name-face ((t (:foreground "#aaaaff"))))
     (nxml-element-prefix-face ((t (:foreground "#884488"))))
     (nxml-text-face ((t (:foreground "green"))))
     (preview-face ((((background dark)) (:background "#667766"))))
     (rng-error-face ((t (:background "red"))))
     (rst-level-3-face ((t (:background "grey71" :foreground "black"))))
     (rst-level-5-face ((t (:background "black"))))
     (show-paren-match ((((class color) (background dark)) (:background "#ff3300" :foreground "black"))))
     (trailing-whitespace ((((class color) (background dark)) (:background "red1" :underline t))))
     (tuareg-font-lock-governing-face ((t (:foreground "orange"))))
     (vertical-border ((((type tty)) (:background "#555555" :foreground "#555555"))))
     (w3-style-face-00000 ((t (:underline nil :weight normal :family "terminus"))))
     (w3-style-face-00016 ((t (:foreground "blue" :underline nil :weight normal :family "courier"))))
     (widget-inactive ((t (:inherit shadow :background "#448844"))))
     (yaml-tab-face ((t (:background "black" :foreground "black" :weight bold))))
     )
   )
  )
